{{- if .Values.networkPolicy.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: default-deny
  namespace: {{ .Values.namespaces.soc }}

spec:
  podSelector: {}

  policyTypes:
    - Ingress

{{- end }}