{{- if .Values.soc.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: soc-service
  namespace: {{ .Values.namespaces.soc }}

spec:
  selector:
    app: soc

  ports:
    - port: {{ .Values.soc.service.port }}
      targetPort: 5000

  type: {{ .Values.soc.service.type }}

{{- end }}